# Site settings
title: Ethan Chiou
description: Hello there.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "echiou.com" # the base hostname & protocol for your site
github_username: echiou

# Build settings
markdown: kramdown
permalink: pretty

paginate: 1
pagination_path: "/blog"
paginate_path: "/blog/:num/"

# collections
collections:
  work:
    output: true
    permalink: /work/:path/
