# Site settings
title: Ethan Chiou
email: your-email@domain.com
description: Hello there.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "echiou.github.io" # the base hostname & protocol for your site
github_username: echiou
flickr_username: echiou

# Build settings
markdown: kramdown
